### ISSUE TITLE
'GetDeveroomTagForCaret: Snapshot version mismatch' when tables are auto formatted

### ISSUE THREAD

**Issue by jamesbellerue** [SpecFlowOSS/SpecFlow.VS#20]
Using SpecFlow for Visual Studio 2022, version 2021.0.200.43519.

When I'm writing out tables in a feature file, I will often get "Warning: GetDeveroomTagForCaret: Snapshot version mismatch" in the Output window under SpecFlow.  It seems to happen when I type a pipe character (as the column delimiter) and the table auto formats itself.  

If I type, say, a column name, wait a second and then type the pipe character, the warning doesn't show up.  It's only when I'm typing relatively quickly that the warning appears.

I wouldn't mind the warning so much except it steals focus from the editor to the Output window, so I have to go click to get back to where I was and continue typing.  There doesn't seem to be an obvious way to turn off the warning, and if I close the Output window it just loads again the next time the warning is generated.

**Comment by rent-a-developer** [comment]
I have the exact same problem.
I too don't mind the warning, but the fact that VS is redirecting the keyboard focus to the output window is interrupting me every time, which is a bit annoying.
I would highly appreciate it when this issue would get fixed.

**Comment by tparikka** [comment]
Note: This has also been reported at https://github.com/SpecFlowOSS/SpecFlow.VisualStudio/issues/199

**Comment by tparikka** [comment]
@gasparnagy I have no experience with WPF, but I've been taking a look at this. In DeveroomEditorCommandBase.GetDeveroomTagForCaret, it looks like we are comparing what we got from the WPF TextView's current buffer to what the TextView's most recent snapshot of its contents is, and if they do not match we rebuild the cache of the tagger object. What I'm seeing when I debug is that if someone is typing rapidly that condition will very frequently be true because the processing of characters in the extension simply can't keep up with the actual WPF view's own processing of the component's contents. There could be a better long term solution that might be architectural in nature but I don't know what that would be and don't have enough time to go digging - would it be a reasonable solution to simply LogInfo instead of LogWarning?

**Comment by gasparnagy** [comment]
@tparikka Thx for the quick analysis. As you said, the proper solution would require architectural changes, but the real impact of this problem is minimal, because the only command that can be physically performed so rapidly after typing is the table autoformat and in the worse case we will just miss a leading whitespace or `|` character.

So my suggestion is: for now, just change the message to `LogInfo` (that closes this issue) and I will add a new issue so that we reconsider the architectural change in one of the later releases.

**Comment by gasparnagy** [comment]
@tparikka FYI: We have discussed it with @patiqs, who is currently preparing the next release and he included the logging change that would be required to avoid the warning popup. So no need to create a PR for that from your side.

**Comment by patiqs** [comment]
I released 2021.1.2 today. Can you validate?
