### ISSUE TITLE
Getting error 'Unable find Specflow tools folder :' when saving a feature file in VS2022

### ISSUE THREAD

**Issue by RohitVegesna** [SpecFlowOSS/SpecFlow.VS#28]
Dear Team,

Recently I installed VS2022 along with specflow extension for VS2022. Whenever I try to save (either Ctrl+S or Save button in VS) a feature file, I keep on getting the below popup message.
![image](https://user-images.githubusercontent.com/75778145/142884094-b7485754-1fc8-4fa3-94c0-2bb2b29a4f7a.png)
Its kind of bit annoying, that I get this message everytime

Is there any possible fix or suggested workaround for me to get this issues fixed ?
However, I am not facing any issue when performing same operation in VS2019

Appreciate your kind response !!

**Comment by patiqs** [comment]
Do you observe the same after building the solution?

**Comment by RohitVegesna** [comment]
@patiqs Yes, I even tried below
1. Cleaning and rebuilding the solution
2. Uninstalled specflow extension and reinstalled it
Nothing helps !!

**Comment by patiqs** [comment]
Does your project use SF3.9.22? If so please try to upgrade to 3.9.40. Let's see if it helps

**Comment by RohitVegesna** [comment]
Still doesn't help even after upgrading the specflow
![image](https://user-images.githubusercontent.com/75778145/143228700-22190011-ec35-44ab-b11b-c6bb386ca1cc.png)

I tried to reproduce with below steps:
1. Create a new xUnit project using VS2019 having specflow extension for VS2019 
2. Add Specflow and Specflow.Xunit latest nuget package
3. Add a sample Feature file and a sample test step definition file
4. Build the solution
5. Close VS2019
6. Open the same solution with VS2022 (it should have Specflow VS2022 extension)
7. Try to save the existing feature file which was created using VS2019

I get an error after step 7
Note: Not getting error in VS2022, if the feature was created using VS2022 itself. Couldn't understand the reason.

Hope it helps for troubleshooting !!

**Comment by gasparnagy** [comment]
@RohitVegesna It seems that the feature files of your project has the design-time feature file code-behind feature enabled, that is not compatible with SpecFlow v3. You can verify that by selecting your feature file in the solution explorer, open the properties (F4) and check the "Custom Tool" setting. That setting should be empty. If it is not empty, then delete the value from there. 

Please let us know if clearing the "Custom Tool" setting solves the problem?

**Comment by gasparnagy** [comment]
@RohitVegesna It's a good question why it was working with VS2019, I think it had a fallback mechanism that somehow found an old SpecFlow version and generated the code behind with that (which has been overwritten by the build). But since it was not using the right version of the generator it was anyway an incorrect. The VS2022 does not have such a fallback logic.

To fix, you can either remove this setting manually (you can multiselect all feature files and remove it as one step), or if you use new-style project files, just simply open the project file as XML and remove all references to feature files and code behind files. With SpecFlow v3 and new project file format you don't need to list feature files individually in the project file (witch is great for merging changes). This fix is backwards compatible with VS2019, so the "fixed" project will also work fine with VS2019 as well.

**Comment by RohitVegesna** [comment]
@gasparnagy Thank you for writing a detailed explanation.
We shall remove the custom property to all features. 
Closing the issue as the proposed solution works.

**Comment by dcdraper** [comment]
I had this issue as well and I took the approach suggested by @gasparnagy to update the project file as XML and remove all references to feature files and code behind files.  This worked great, thanks!
